enum WallType {
    TOP = "TOP",
    LEFT = "LEFT",
    RIGHT = "RIGHT",
    BOTTOM = "BOTTOM",

    CONCAVE_CORNER_TOP_LEFT = "CONCAVE_CORNER_TOP_LEFT",
    CONCAVE_CORNER_TOP_RIGHT = "CONCAVE_CORNER_TOP_RIGHT",
    CONCAVE_CORNER_BOTTOM_LEFT = "CONCAVE_CORNER_BOTTOM_LEFT",
    CONCAVE_CORNER_BOTTOM_RIGHT = "CONCAVE_CORNER_BOTTOM_RIGHT",

    CONVEX_CORNER_BOTTOM_LEFT = "CONVEX_CORNER_BOTTOM_LEFT",
    CONVEX_CORNER_TOP_LEFT = "CONVEX_CORNER_TOP_LEFT",
    CONVEX_CORNER_TOP_RIGHT = "CONVEX_CORNER_TOP_RIGHT",
    CONVEX_CORNER_BOTTOM_RIGHT = "CONVEX_CORNER_BOTTOM_RIGHT",
}

export default WallType;